import { expect, test } from '@playwright/test'
import { openLab, selectSurface } from './helpers'

test('Atelier rail is bounded and layered mark respects reduced motion', async ({ page }) => {
 const frame = await openLab(page)
 await page.locator('#lab-design-select').selectOption('atelier')
 await selectSurface(page, 'Home')
 const root = frame.locator('[data-template="atelier"]')
 await expect(root).toBeVisible()
 await expect(root).not.toContainText('↗')
 await expect(root).not.toContainText('Edition 01')
 await expect(root).not.toContainText('01 / HOME')
 const destination = root.getByRole('navigation', {name: 'Explore', exact: true}).locator('a').first()
 await destination.hover()
 await expect.poll(() => destination.evaluate(el => getComputedStyle(el).textDecorationColor)).not.toBe('rgba(0, 0, 0, 0)')
 const mark = root.locator('span[aria-hidden="true"]').filter({hasText: /^A$/}).last()
 await expect(mark).toBeVisible()
 await expect.poll(() => root.locator('aside').first().evaluate(el => el.getBoundingClientRect().width)).toBeLessThanOrEqual(238)
 await page.emulateMedia({reducedMotion: 'reduce'})
 await expect.poll(() => root.locator('h1').evaluate(el => getComputedStyle(el.parentElement!).animationName)).toBe('none')
 await root.screenshot({path: 'test-results/atelier-refinement.png'})
})

test('Atelier stays installed across surfaces, Studio changes, and iframe reload',async({page})=>{
 const frame=await openLab(page)
 await page.locator('#lab-design-select').selectOption('atelier')
 await expect(frame.locator('[data-template="atelier"]')).toBeVisible()
 await selectSurface(page,'Records')
 await frame.getByRole('searchbox',{name:'Search records'}).fill('no-such-record-portability-check')
 await expect(frame.getByText('No records match this view.')).toBeVisible()
 await selectSurface(page,'Character profile')
 await expect(frame.locator('[data-template="atelier"] h1')).toBeVisible()
 await page.getByRole('tab',{name:'Studio',exact:true}).click()
 await page.getByRole('combobox',{name:'Master palette',exact:true}).selectOption('plum')
 await expect.poll(()=>frame.locator('[data-template="atelier"]').evaluate(el=>getComputedStyle(el).getPropertyValue('--atelier-paper').trim())).toBe('#ecd2ce')
 await frame.goto(frame.url())
 await expect(frame.locator('[data-template="atelier"] h1')).toBeVisible()
 await expect(page.locator('#lab-design-select')).toHaveValue('atelier')
 await expect.poll(()=>frame.locator('[data-template="atelier"]').evaluate(el=>getComputedStyle(el).getPropertyValue('--atelier-paper').trim())).toBe('#ecd2ce')
})

test('Atelier Studio palettes, spacing, fonts and rules affect the rendered site',async({page})=>{
 const frame=await openLab(page)
 await page.locator('#lab-design-select').selectOption('atelier')
 await selectSurface(page,'Home')
 await page.getByRole('tab',{name:'Studio',exact:true}).click()
 const root=frame.locator('[data-template="atelier"]')
 for(const [key,color] of Object.entries({parchment:'#f1ecdf',coast:'#ffffff',botanical:'#182f27',plum:'#ecd2ce',midnight:'#11141b'})){
  await page.getByRole('combobox',{name:'Master palette',exact:true}).selectOption(key)
  await expect.poll(()=>root.evaluate(el=>getComputedStyle(el).getPropertyValue('--atelier-paper').trim())).toBe(color)
  await expect.poll(()=>root.locator('aside').first().evaluate(el=>getComputedStyle(el).backgroundColor)).toBe(({parchment:'rgb(41, 43, 40)',coast:'rgb(225, 237, 255)',botanical:'rgb(229, 223, 196)',plum:'rgb(72, 43, 70)',midnight:'rgb(9, 11, 16)'} as Record<string,string>)[key])
 }
 await page.getByRole('combobox',{name:'Spacing',exact:true}).selectOption('airy')
 await expect.poll(()=>root.locator('main').evaluate(el=>getComputedStyle(el).paddingTop)).toBe('64px')
 await page.getByRole('combobox',{name:'Dividers',exact:true}).selectOption('3')
 await expect.poll(()=>root.getByRole('navigation',{name:'Explore',exact:true}).locator('a').first().evaluate(el=>getComputedStyle(el).borderTopWidth)).toBe('3px')
 await page.getByRole('combobox',{name:'Typography',exact:true}).selectOption('technical')
 await expect.poll(()=>root.locator('h1').evaluate(el=>getComputedStyle(el).fontFamily)).toContain('Courier')
 await page.emulateMedia({reducedMotion:'reduce'})
 await root.screenshot({path:'test-results/atelier-midnight.png'})
})

test('Page color pickers apply exact values even across low contrast combinations',async({page})=>{
 const frame=await openLab(page)
 await page.locator('#lab-design-select').selectOption('atelier')
 await selectSurface(page,'Home')
 await page.getByRole('tab',{name:'Studio',exact:true}).click()
 await page.getByRole('combobox',{name:'Master palette',exact:true}).selectOption('parchment')
 const root=frame.locator('[data-template="atelier"]')
 await page.getByLabel('Page background',{exact:true}).fill('#333333')
 await expect.poll(()=>root.locator('main').locator('..').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe('rgb(51, 51, 51)')
 await expect(page.getByRole('status').filter({hasText:'Page text contrast is low'})).toBeVisible()
 await page.getByLabel('Page text',{exact:true}).fill('#eeeeee')
 await expect.poll(()=>root.locator('h1').evaluate(el=>getComputedStyle(el).color)).toBe('rgb(238, 238, 238)')
 await frame.goto(frame.url())
 await expect.poll(()=>root.locator('h1').evaluate(el=>getComputedStyle(el).color)).toBe('rgb(238, 238, 238)')
 await expect.poll(()=>root.locator('main').locator('..').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe('rgb(51, 51, 51)')
})
