import { expect, test } from '@playwright/test'
import { openLab, selectSurface, selectViewport } from './helpers'

test('Atelier folder changes persist across navigation and refresh',async({page})=>{
 const frame=await openLab(page)
 await page.locator('#lab-design-select').selectOption('atelier')
 await selectSurface(page,'Manage Folders')
 await frame.getByLabel('Name',{exact:true}).fill('Atelier browser folder')
 await frame.getByRole('button',{name:'Create folder',exact:true}).click()
 await frame.getByRole('button',{name:'Atelier browser folder',exact:true}).click()
 await frame.getByLabel('Folder name',{exact:true}).fill('Atelier renamed folder')
 await frame.getByRole('button',{name:'Rename folder',exact:true}).click()
 await expect(frame.getByRole('button',{name:'Atelier renamed folder',exact:true})).toBeVisible()
 await selectSurface(page,'Manage People')
 await selectSurface(page,'Manage Folders')
 await frame.getByRole('button',{name:'Atelier renamed folder',exact:true}).click()
 await frame.getByText('Move folder',{exact:true}).first().click()
 await frame.getByRole('combobox',{name:'Destination',exact:true}).selectOption({label:'Domain root'})
 await frame.getByRole('button',{name:'Move folder',exact:true}).click()
 await frame.goto(frame.url())
 await frame.getByRole('button',{name:'Atelier renamed folder',exact:true}).click()
 await frame.locator('summary').filter({hasText:'Delete folder'}).click()
 page.once('dialog',dialog=>dialog.accept())
 await frame.getByRole('button',{name:'Delete folder',exact:true}).click()
 await expect(frame.getByRole('button',{name:'Atelier renamed folder',exact:true})).toHaveCount(0)
})

test('Atelier type creation, people navigation, and invitation actions work in the browser',async({page})=>{
 const errors:string[]=[]
 page.on('pageerror',error=>errors.push(error.message))
 const frame=await openLab(page)
 await page.locator('#lab-design-select').selectOption('atelier')
 await selectSurface(page,'Document Types')
 await frame.getByRole('button',{name:'New document type',exact:true}).click()
 await frame.getByPlaceholder('e.g. Deed of Transfer').fill('Atelier browser type')
 const department=frame.locator('select[title^="The Department root"]')
 await department.selectOption({index:1})
 await frame.getByRole('button',{name:'Create Type',exact:true}).click()
 await expect(frame.getByRole('button',{name:'Atelier browser type',exact:true})).toBeVisible()
 await selectSurface(page,'Manage People')
 await frame.getByRole('combobox',{name:'Search people'}).fill('a')
 await expect(frame.getByRole('listbox',{name:'People'}).getByRole('option').first()).toBeVisible()
 await frame.getByRole('combobox',{name:'Search people'}).press('ArrowDown')
 await frame.getByRole('combobox',{name:'Search people'}).press('Enter')
 await expect(frame.getByRole('heading',{name:'Effective document access'})).toBeVisible()
 await selectSurface(page,'Manage Invitations')
 await frame.getByRole('button',{name:'Create invitation',exact:true}).click()
 await expect(frame.getByRole('status').filter({hasText:'Copy and share'})).toBeVisible()
 await selectViewport(page,'Phone wide',390,844)
 await expect.poll(()=>frame.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 expect(errors).toEqual([])
})
