import { createHash } from 'node:crypto'
import { copyFileSync, existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const designRoot = path.join(root, 'src', 'designs')
const outputRoot = path.join(root, 'src', 'lib', 'design', 'generated')
const publicRoot = path.join(root, 'public', 'design-assets')
const check = process.argv.includes('--check')

function fail(message) { throw new Error(`[design discovery] ${message}`) }
function sha256(file) { return createHash('sha256').update(readFileSync(file)).digest('hex') }
function writeOrCheck(file, contents) {
  if (check) { if (!existsSync(file) || readFileSync(file, 'utf8') !== contents) fail(`stale generated output: ${file}`) }
  else { mkdirSync(path.dirname(file), { recursive: true }); writeFileSync(file, contents, 'utf8') }
}
function walkAssets(source, relative = '') {
  const entries = []
  for (const entry of readdirSync(source, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const full = path.join(source, entry.name)
    const next = relative ? `${relative}/${entry.name}` : entry.name
    if (entry.isDirectory()) entries.push(...walkAssets(full, next))
    else if (entry.isFile()) entries.push({ relative: next, full })
    else fail(`unsupported asset entry: ${full}`)
  }
  return entries
}

const manifests = readdirSync(designRoot, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && existsSync(path.join(designRoot, entry.name, 'design.manifest.json')))
  .map((entry) => {
    const folder = entry.name
    const file = path.join(designRoot, folder, 'design.manifest.json')
    const manifest = JSON.parse(readFileSync(file, 'utf8'))
    if (manifest.key !== folder || manifest.entry !== './index.ts' || manifest.manifestVersion !== 1 || manifest.designContractVersion !== 1) fail(`invalid manifest: ${file}`)
    if (!existsSync(path.join(designRoot, folder, 'index.ts'))) fail(`missing entry: ${folder}`)
    if (!manifest.preview?.thumbnail?.startsWith('assets/')) fail(`thumbnail must be bundled: ${folder}`)
    if (!existsSync(path.join(designRoot, folder, manifest.preview.thumbnail))) fail(`missing thumbnail: ${folder}`)
    return manifest
  })
  .sort((a, b) => (a.sortOrder ?? Number.MAX_SAFE_INTEGER) - (b.sortOrder ?? Number.MAX_SAFE_INTEGER) || a.key.localeCompare(b.key))

if (manifests.length === 0) fail('no installable Design manifests discovered')
const keys = manifests.map((manifest) => manifest.key)
const keySource = `// AUTO-GENERATED by scripts/discover-designs.mjs. Do not edit.\n\nexport const DESIGN_KEYS = [\n${keys.map((key) => `  ${JSON.stringify(key)},`).join('\n')}\n] as const\nexport type DesignKey = (typeof DESIGN_KEYS)[number]\nexport function isDesignKey(value: unknown): value is DesignKey { return typeof value === 'string' && (DESIGN_KEYS as readonly string[]).includes(value) }\n`
const catalogSource = `import type { DesignKey } from '../types'\nimport type { DesignStatus } from '../contracts'\nexport type DesignCatalogEntry = { key: DesignKey; status: DesignStatus; name: string; description: string; thumbnail: string }\nexport const DESIGN_CATALOG: readonly DesignCatalogEntry[] = [\n${manifests.map((manifest) => `  { key: ${JSON.stringify(manifest.key)}, status: ${JSON.stringify(manifest.status)}, name: ${JSON.stringify(manifest.name)}, description: ${JSON.stringify(manifest.description)}, thumbnail: ${JSON.stringify(`/design-assets/${manifest.key}/${manifest.preview.thumbnail.slice('assets/'.length)}`)} },`).join('\n')}\n]\nexport const DESIGN_CATALOG_KEYS: readonly DesignKey[] = DESIGN_CATALOG.map((entry) => entry.key)\nexport const FIRST_CLASS_DESIGNS: readonly DesignKey[] = DESIGN_CATALOG.filter((entry) => entry.status === 'first-class').map((entry) => entry.key)\n`
const registrySource = `import type { DesignDefinition, DesignKey } from '../types'\n${manifests.map((manifest, index) => `import design_${index} from '@/designs/${manifest.key}'`).join('\n')}\nimport { DESIGN_KEYS, isDesignKey } from './designKeys'\nimport { DESIGN_CATALOG, type DesignCatalogEntry } from './catalog'\nfunction eraseConfig<T extends object>(definition: DesignDefinition<T>): DesignDefinition { return definition as unknown as DesignDefinition }\nexport const DESIGNS: Record<DesignKey, DesignDefinition> = { ${manifests.map((manifest, index) => `${JSON.stringify(manifest.key)}: eraseConfig(design_${index})`).join(', ')} }\ntype RegistryGlobals = { __loreforgeLabRegistryOverride?: Map<string, unknown> }\nfunction getLegacyTestOverride(): DesignDefinition[] | null {\n  const override = (globalThis as unknown as RegistryGlobals).__loreforgeLabRegistryOverride\n  return override ? [...override.values()] as DesignDefinition[] : null\n}\nexport function getDesignDefinitions(): DesignDefinition[] { return getLegacyTestOverride() ?? DESIGN_KEYS.map((key) => DESIGNS[key]) }\nexport function getDesignDefinition(key: string): DesignDefinition | undefined {\n  const override = getLegacyTestOverride()\n  return override?.find((definition) => definition.key === key) ?? (isDesignKey(key) ? DESIGNS[key] : undefined)\n}\nexport const DESIGN_METADATA: DesignCatalogEntry[] = DESIGN_KEYS.map((key) => ({ ...DESIGN_CATALOG.find((entry) => entry.key === key)! }))\n`
writeOrCheck(path.join(outputRoot, 'designKeys.ts'), keySource)
writeOrCheck(path.join(outputRoot, 'catalog.ts'), catalogSource)
writeOrCheck(path.join(outputRoot, 'registry.ts'), registrySource)

const expectedAssets = new Map()
for (const manifest of manifests) {
  const source = path.join(designRoot, manifest.key, 'assets')
  if (!existsSync(source) || !lstatSync(source).isDirectory()) fail(`missing assets directory: ${source}`)
  for (const asset of walkAssets(source)) expectedAssets.set(`${manifest.key}/${asset.relative}`, asset.full)
}
if (check) {
  const actual = existsSync(publicRoot) ? walkAssets(publicRoot).map((asset) => `${asset.relative}:${sha256(asset.full)}`) : []
  const expected = [...expectedAssets.entries()].map(([relative, file]) => `${relative}:${sha256(file)}`).sort()
  if (actual.sort().join('\n') !== expected.join('\n')) fail(`stale generated assets: ${publicRoot}`)
} else {
  mkdirSync(publicRoot, { recursive: true })
  for (const entry of readdirSync(publicRoot, { withFileTypes: true })) if (!manifests.some((manifest) => manifest.key === entry.name)) rmSync(path.join(publicRoot, entry.name), { recursive: true, force: true })
  for (const [relative, source] of expectedAssets) { const target = path.join(publicRoot, relative); mkdirSync(path.dirname(target), { recursive: true }); copyFileSync(source, target) }
}
console.log(`${check ? 'checked' : 'discovered'} ${keys.length} Design(s): ${keys.join(', ')}`)
